FROM maven:3.9.4-eclipse-temurin-17

WORKDIR /workspace

COPY pom.xml .
COPY flightappcommon flightappcommon
COPY configserver configserver
COPY eureka-server eureka-server
COPY authservice authservice
COPY flightservice flightservice
COPY bookingservice bookingservice
COPY emailservice emailservice
COPY apigateway apigateway

RUN mvn -B -DskipTests clean install
