server:
  port: 8200

spring:
  application:
    name: bookingservice
    mail:
      host: smtp.gmail.com
      port: 587
      username: sravanthigurram955@gmail.com
      password: Srav@22bce2020     
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true


  data:
    mongodb:
      uri: mongodb://localhost:27017/bookingdb

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      flight:
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
		
		
		
		
		  
