server:
  port: 8100

spring:
  application:
    name: flightservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/flightdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      flight-service:
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
